# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b61aa5cfcf886df3b598387b465deb117969270e4ea7bd7c4fc7ed700d7d9afdbc5a4fa8c32a1a1c3d8b142b16e7c6e911b94443ff55b28eb4232a8f2e61275d

test:
  secret_key_base: 48e76a6ec1e3395cb4a241e386f12d3ab09dda1c4a560b54c8bd51888cca6fd91fd54c3ce7d3657d2bf4d1552db4eb01dcd3276ac5f82c4610122f53dbfad176

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
